# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Menu Services 4
  description: Menu Services 4
  icon: 'cottage'

# Defines the structure of this component, as well as the default values
blueprint:
  status: true
  title: NAIL LAB SIGNATURE COCKTAILS
  is_two_column: false
  menu:
    - name: Mimosa Fizz Delight
      description: '<span style="font-weight: 400;">Experience a delightful fusion of crisp, chilled champagne and freshly squeezed orange juice. This classic concoction is the epitome of brunch elegance, boasting a perfect balance of bubbly sophistication and vibrant citrus notes.</span>'

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  title:
    type: text
    label: Title
  is_two_column:
    type: toggle
    label: Two Column Layout
  menu[*].name:
    type: text
    label: Name
  menu[*].description:
    type: markdown
    label: Description
