# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Menu Services 1
  description: Menu Services 1
  icon: 'cottage'

# Defines the structure of this component, as well as the default values
blueprint:
  status: true
  title: PEDICURE
  name: NAIL LAB
  background_color: '#11141d'
  image: '/images/menu1.png'
  image_alt: menu 1
  description: '<div class="elementor-widget-container"><p><i><span style="font-weight: 400;">Pink Himalayan Salt, rich in nutrients and minerals, aids in various skin conditions such as acne treatment, psoriasis, and eczema. It also provides pain relief, decreases stress, enhances blood circulation, promotes detoxification, aids in sleep, exfoliates the skin, removes splinters, relaxes tired muscles, softens skin, assists in weight loss by expelling excess water from cells, detoxifies the skin, and promotes skin brightening.</span></i></p><p><i><span style="font-weight: 400;">The detox scrub helps diminish swelling, soothe the body, and harmonize your energy.</span></i></p>								</div>'
  menu:
    - name: Classic Pedicure
      price: 38
      description: <p class="elementor-price-list-description">Swift, essential foot care. Includes basic cleanup and gentle massage with a warm towel.</p>
    - name: Lavish Pedicure
      price: 45
      description:
        A contemporary take on the classic pedicure. Immerse your feet in a relaxing soak,
        followed by a sugar scrub to enhance blood circulation,
        and a warm towel treatment along with callus treatment.,

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  title:
    type: text
    label: Content
  image:
    type: image
    label: Image 1
  image_alt:
    type: text
    label: Image 1 Alt Text
  background_color:
    type: color
    label: Background Color
  menu[*].name:
    type: text
    label: Name
  menu[*].price:
    type: number
    label: Price
  menu[*].description:
    type: markdown
    label: Description
