# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Breadcrumb Section
  description: Breadcrumb Section
  icon: 'cottage'

# Defines the structure of this component, as well as the default values
blueprint:
  status: true
  background_color: '#11141d'
  title: Our Place
  sub_title: NAIL LAB
  style: false

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  sub_title:
    type: text
    label: Sub Title
  button.label:
    type: text
    label: Label
  style:
    type: toggle
    label: Style
