# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Comment Section
  description: Comment Section
  icon: 'cottage'

# Defines the structure of this component, as well as the default values
blueprint:
  status: true
  title: What customers say about us?
  background_color: '#11141d'
  background_image: '/images/background_section_comment.png'
  list_items:
    - author: Sarah
      avatar: '/images/background_section_comment.png'
      description: 'The service was amazing! The staff was very professional and my nails look beautiful.'
    - author: Jessica
      avatar: '/images/background_section_comment.png'
      description: "I can't believe I got my nails done at Nail Lab! They were so friendly and professional."
    - author: Laura
      avatar: '/images/background_section_comment.png'
      description: 'I absolutely loved the design and the attention to detail in my nails. The staff was also great.'

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  title:
    type: markdown
    label: Title
  list_images[*].author:
    type: text
    label: Author's Name
  list_images[*].avatar:
    type: image
    label: Author's Avatar
  list_images[*].description:
    type: markdown
    label: Description
