# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Contact Section
  description: Contact Section
  icon: 'cottage'

# Defines the structure of this component, as well as the default values
blueprint:
  status: true
  logo: '/images/logo.png'
  logo_alt: NAIL LAB
  button:
    is_show: true
    label: 'Contact us'
    open_new_tab: true
    link: '/contact'

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  logo:
    type: image
    label: Logo
  logo_alt:
    type: text
    label: Logo Alt
  button.label:
    type: text
    label: Label
  button.link:
    type: text
    label: Link
