# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Editor Section
  description: Editor Section
  icon: "cottage"

# Defines the structure of this component, as well as the default values
blueprint:
  status: true
  background_color: '#ffffff'
  content: ""

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  status:
    label: Active Section
    type: toggle
  background_color:
    label: Background Color Section
    type: color
  content:
    label: Content
    type: markdown
