# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Hero Section
  description: Hero Section
  icon: 'cottage'

# Defines the structure of this component, as well as the default values
blueprint:
  status: true
  background_color: '#11141d'
  description: 'Experience the Grace and Beauty at NAIL LAB'
  image_1: /images/model-abc.png
  image_alt_1: 'Image Hero 1'
  image_2: /images/mani.svg
  image_alt_2: 'Image Hero 2'
  image_3: /images/Asset-1.png
  image_alt_3: 'Image Hero 3'
  button:
    is_show: true
    label: 'Booking Now'
    open_new_tab: true
    link: '/#'

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  description:
    type: markdown
    label: Content
  image_1:
    type: image
    label: Image 1
  image_2:
    type: image
    label: Image 2
  image_3:
    type: image
    label: Image 3
  image_alt_1:
    type: text
    label: Image 1
  image_alt_2:
    type: text
    label: Image 2
  image_alt_3:
    type: text
    label: Image 3
  button.label:
    type: text
    label: Label
  button.link:
    type: text
    label: Link
