# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Service Section
  description: Service Section
  icon: 'cottage'

# Defines the structure of this component, as well as the default values
blueprint:
  status: true
  title: Our Services
  sub_title: NAIL LAB
  button:
    is_show: true
    label: 'View All Services'
    background_items: '#11141d'
    open_new_tab: true
    link: '/services'
  list_items:
    - image: /images/mani.svg
      title: Manicure
      image_alt: Nail service 1
      link: /services/#mani

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  title:
    type: text
    label: Title
  sub_title:
    type: text
    label: Name Store
  background_items:
    type: color
    label: Background Items
  list_images[*].title:
    type: text
    label: Title 1
  list_images[*].image:
    type: image
    label: Image 1
  list_images[*].image_alt:
    type: text
    label: Image Alt
  list_images[*].link:
    type: text
    label: Link
  button.label:
    type: text
    label: Label
  button.link:
    type: text
    label: Link
