# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Contact Hero
  description: Contact Hero
  icon: 'cottage'

# Defines the structure of this component, as well as the default values
blueprint:
  status: true
  title: Get in touch and let us know how we can help.
  background_color: '#11141d'
  menu_items:
    - image: '/images/location-pointer-2961.svg'
      content: (919) 336-9999
      link: '/'
  form:
    title: Send us a message
    background_color: '#fff'
    color: '#000'
    background_color_btn: '#000'
    color_btn: '#fff'
    list_fields:
      - fields: text
        status_error: true
        error: Please this is a required field.
        label: First Name
        placehoder: Please enter first name
        width_fields: 1/2
      - fields: text
        status_error: true
        error: Please this is a required field.
        label: Last Name
        placehoder: Please enter last name
        width_fields: 1/2
      - fields: email
        status_error: true
        error: Please this is a required field.
        label: Email
        placehoder: Please enter email
        width_fields: full
      - fields: tel
        status_error: true
        error: Please this is a required field.
        label: Phone Number
        placehoder: Please enter phone number
        width_fields: full
      - fields: textarea
        status_error: true
        error: Please this is a required field.
        label: Message
        placehoder: Please enter message
        width_fields: full
      - fields: file
        status_error: true
        error: Please this is a required field.
        label: Attachments 2 (for Resume, References, etc)
        placehoder: PNG, JPG or PDF, smaller than 15MB dasds
        width_fields: full

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  title:
    type: text
    label: Title
  sub_title:
    type: text
    label: Sub Title
  background_color:
    type: color
    label: Background Color
  title_button:
    type: text
    label: Title Button Text
  address:
    type: text
    label: Address
  mail:
    type: text
    label: Email
  phone:
    type: text
    label: Phone Number

  form.title:
    type: text
    label: Form Title
  form.background_color:
    type: color
    label: Form Background Color
  form.color:
    type: color
    label: Form Text Color
  form.background_color_btn:
    type: color
    label: Form Button Background Color
  form.color_btn:
    type: color
    label: Form Button Text Color
  form.list_fields[*].fields:
    label: Type Fields
    type: select
    description:
    options:
      - text
      - textarea
      - email
      - tel
      - file
  form.list_fields[*].error:
    label: Text Required
    type: text
  form.list_fields[*].status_error:
    label: Required
    type: toggle
  form.list_fields[*].label:
    label: Label
    type: text
  form.list_fields[*].placehoder:
    label: Placehoder
    type: text
  form.list_fields[*].width_fields:
    label: Width Fields
    type: select
    options:
      - full
      - 1/2
