# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Contact Hero
  description: Contact Hero
  icon: 'cottage'

# Defines the structure of this component, as well as the default values
blueprint:
  status: true
  title: NAIL LAB
  sub_title: Get in touch and let us know how we can help.
  background_color: '#11141d'
  menu_items:
    - image: '/images/location-pointer-2961.svg'
      content: (919) 336-9999
      link: '/'
  title_form: Send us a message
  background_color_form: '#ffffff'
  color_form: '#000000'
  background_color_btn: '#000000'
  color_btn: '#ffffff'
  list_fields:
    - fields: text
      status_error: true
      error: Please this is a required field.
      label: First Name
      placehoder: Please enter first name
      width_fields: 1/2
    - fields: tel
      status_error: true
      error: Please this is a required field.
      label: Phone Number
      placehoder: Please enter phone number
      width_fields: 1/2
    - fields: email
      status_error: true
      error: Please this is a required field.
      label: Email
      placehoder: Please enter email
      width_fields: full
    - fields: textarea
      status_error: true
      error: Please this is a required field.
      label: Message
      placehoder: Please enter message
      width_fields: full
    - fields: file
      status_error: true
      error: Please this is a required field.
      label: Attachments 2 (for Resume, References, etc)
      placehoder: PNG, JPG or PDF, smaller than 15MB dasds
      width_fields: full
    - fields: file
      status_error: true
      error: Please this is a required field.
      label: Attachments 2 (for Resume, References, etc)
      placehoder: PNG, JPG or PDF, smaller than 15MB dasds
      width_fields: full

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  title:
    type: markdown
    label: Title
  sub_title:
    type: markdown
    label: Sub Title
  background_color:
    type: color
    label: Background Color
  address:
    type: text
    label: Address
  mail:
    type: text
    label: Email
  phone:
    type: text
    label: Phone Number
  title_form:
    type: markdown
    label: Form Title
  background_color_form:
    type: color
    label: Form Background Color
  color_form:
    type: color
    label: Form Text Color
  background_color_btn:
    type: color
    label: Form Button Background Color
  color_btn:
    type: color
    label: Form Button Text Color
  list_fields[*].fields:
    label: Type Fields
    type: select
    description:
    options:
      - text
      - textarea
      - email
      - tel
      - file
  list_fields[*].error:
    label: Text Required
    type: text
  list_fields[*].status_error:
    label: Required
    type: toggle
  list_fields[*].label:
    label: Label
    type: text
  list_fields[*].placehoder:
    label: Placehoder
    type: text
  list_fields[*].width_fields:
    label: Width Fields
    type: select
    options:
      - full
      - 1/2
