# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Contact Hero
  description: Contact Hero
  icon: 'cottage'

# Defines the structure of this component, as well as the default values
blueprint:
  status: true
  title: Get in touch and let us know how we can help.
  background_color: '#11141d'
  map: '<iframe
    src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d30669.193637388995!2d-78.603077!3d35.900957!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89ac5752d88602b3%3A0xf4b931a748e2dc2c!2sNAIL%20LAB%20-%20Luxury%20Nail%20Bar!5e1!3m2!1sen!2sus!4v1741341715935!5m2!1sen!2sus"
    width="100%"
    height="485"
    style="border: 0"
    loading="lazy"
    referrerpolicy="no-referrer-when-downgrade"
    ></iframe>'
  menu_items:
    - image: '/images/location-pointer-2961.svg'
      content: (919) 336-9999
      link: '/'

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  title:
    type: text
    label: Title
  sub_title:
    type: text
    label: Sub Title
  background_color:
    type: color
    label: Background Color
  title_button:
    type: text
    label: Title Button Text
  address:
    type: text
    label: Address
  mail:
    type: text
    label: Email
  phone:
    type: text
    label: Phone Number
  map:
    type: textarea
    label: Google Map
