# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Contact Hero
  description: Contact Hero
  icon: 'cottage'

# Defines the structure of this component, as well as the default values
blueprint:
  status: true
  title: Get in touch and let us know how we can help.
  background_color: '#11141d'
  menu_items:
    - image: '/images/location-pointer-2961.svg'
      content: (919) 336-9999
      link: '/'

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  title:
    type: text
    label: Title
  sub_title:
    type: text
    label: Sub Title
  background_color:
    type: color
    label: Background Color
  title_button:
    type: text
    label: Title Button Text
  address:
    type: text
    label: Address
  mail:
    type: text
    label: Email
  phone:
    type: text
    label: Phone Number
  form_width:
    label: Width Form
    type: select
    options:
      - full
      - 1/2
  form:
    label: Form Contact
    description: Add new form fields.
  form[*].background_color:
    label: Form Background Color
    type: color
    description:
    options:
      - contact
  form[*].fields:
    label: Type Fields
    type: select
    description:
    options:
      - text
      - textarea
      - email
      - tel
      - file
  form[*].error:
    label: Text Required
    type: text
  form[*].status_error:
    label: Required
    type: toggle
  form[*].label:
    label: Label
    type: text
  form[*].placehoder:
    label: Placehoder
    type: text
  form[*].width_fields:
    label: Width Fields
    type: select
    options:
      - full
      - 1/2
  button.text_button:
    label: Button Text
    type: text
  button.background:
    label: Background Color
    type: color
  button.color:
    label: Text Color
    type: color
  button.border:
    label: Border Radius
    type: text
  button.variant:
    label: Variant Button
    type: select
    options:
      - solid
      - outline
  button.width_button:
    label: Width Button
    type: select
    options:
      - auto
      - 1/2
      - 1/3
      - 1/4
      - full
  button.align_button:
    label: Align Button
    type: select
    options:
      - left
      - right
      - center
